; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName         "Qt Linguist for Web"    
#define MyAppExeNameJs    "lupdate-js.exe"
#define MyAppExeNamePhp   "lupdate-php.exe"    
#define MyAppExeNameQt    "linguist.exe"        
#define MyAppExePathJs    "..\build-lupdate-js\release"
#define MyAppExePathPhp   "..\build-lupdate-php\release"    
#define MyDepenciesPath   "..\windows-dependencies"
#define MyAppVersion      GetVersionNumbersString(MyAppExePathJs + "\" + MyAppExeNameJs)
#define MyAppURL          "https://github.com/GustavLindberg99/QtLinguistWeb"
#define MyAppOutputDir    ".."
#define MyAppOutputExe    "qt-linguist-web-install"
#define MyAppLicenseFile  "license.rtf"
#define MyAppCompany      "Gustav Lindberg"
#define MyAppStartingYear "2024"
#define CurrentYear       GetDateTimeString('yyyy','','')

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2D5D4A1E-D808-48B1-88D8-A00C8064CEA3}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}

AppCopyright=(c) {#MyAppStartingYear}-{#CurrentYear} {#MyAppCompany}
AppPublisher={#MyAppCompany}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

VersionInfoDescription={#MyAppName} installer
VersionInfoProductName={#MyAppName}
VersionInfoVersion={#MyAppVersion}

UninstallDisplayName={#MyAppName}

LicenseFile={#MyAppLicenseFile} 

ShowLanguageDialog=yes
UsePreviousLanguage=no
LanguageDetectionMethod=uilanguage

WizardStyle=modern

DefaultDirName={commonpf64}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir={#MyAppOutputDir}
OutputBaseFilename={#MyAppOutputExe}
Compression=lzma
SolidCompression=yes


[Components]       
Name: "lupdate_js"; Description: "lupdate-js"; Types: full compact custom
Name: "lupdate_php"; Description: "lupdate-php"; Types: full compact custom
Name: "qt_linguist"; Description: "Qt Linguist"; Types: full custom

[Files]  
Source: "{#MyAppExePathJs}\{#MyAppExeNameJs}"; DestDir: "{app}"; Flags: ignoreversion; Components: lupdate_js
Source: "{#MyAppExePathPhp}\{#MyAppExeNamePhp}"; DestDir: "{app}"; Flags: ignoreversion; Components: lupdate_php
Source: "{#MyDepenciesPath}\common\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: lupdate_js lupdate_php qt_linguist  
Source: "{#MyDepenciesPath}\lupdate\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: lupdate_js lupdate_php
Source: "{#MyDepenciesPath}\qt-linguist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: qt_linguist
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}\Qt Linguist"; Filename: "{app}\{#MyAppExeNameQt}"; Components: qt_linguist
