#ifndef LANGUAGES_H
#define LANGUAGES_H

#include <tuple>

inline constexpr const std::tuple<const char*, int, const char*> languages[] = {
    {"aa", 2, "Afar"},
    {"ab", 2, "Abkhazian"},
    {"af", 2, "Afrikaans"},
    {"am", 2, "Amharic"},
    {"ar", 6, "Arabic"},
    {"as", 2, "Assamese"},
    {"az", 2, "Azerbaijani"},
    {"ba", 2, "Bashkir"},
    {"be", 3, "Belarusian"},
    {"bg", 2, "Bulgarian"},
    {"bn", 2, "Bangla"},
    {"bo", 1, "Tibetan"},
    {"br", 2, "Breton"},
    {"bs", 3, "Bosnian"},
    {"ca", 2, "Catalan"},
    {"co", 2, "Corsican"},
    {"cs", 3, "Czech"},
    {"cy", 5, "Welsh"},
    {"da", 2, "Danish"},
    {"de", 2, "German"},
    {"dv", 3, "Divehi"},
    {"dz", 1, "Dzongkha"},
    {"el", 2, "Greek"},
    {"en", 2, "English"},
    {"eo", 2, "Esperanto"},
    {"es", 2, "Spanish"},
    {"et", 2, "Estonian"},
    {"eu", 2, "Basque"},
    {"fa", 1, "Persian"},
    {"fi", 2, "Finnish"},
    {"fil", 2, "Filipino"},
    {"fo", 2, "Faroese"},
    {"fr", 2, "French"},
    {"fur", 2, "Friulian"},
    {"fy", 2, "Western Frisian"},
    {"ga", 3, "Irish"},
    {"gd", 4, "Gaelic"},
    {"gl", 2, "Galician"},
    {"gn", 1, "Guarani"},
    {"gu", 2, "Gujarati"},
    {"gv", 3, "Manx"},
    {"ha", 2, "Hausa"},
    {"he", 2, "Hebrew"},
    {"hi", 2, "Hindi"},
    {"hr", 3, "Croatian"},
    {"hu", 1, "Hungarian"},
    {"hy", 2, "Armenian"},
    {"ia", 2, "Interlingua"},
    {"id", 1, "Indonesian"},
    {"is", 2, "Icelandic"},
    {"it", 2, "Italian"},
    {"iu", 3, "Inuktitut"},
    {"ja", 1, "Japanese"},
    {"jv", 1, "Javanese"},
    {"ka", 2, "Georgian"},
    {"kk", 2, "Kazakh"},
    {"kl", 2, "Kalaallisut"},
    {"kn", 2, "Kannada"},
    {"ko", 1, "Korean"},
    {"ks", 2, "Kashmiri"},
    {"ku", 2, "Kurdish"},
    {"kw", 2, "Cornish"},
    {"ky", 2, "Kyrgyz"},
    {"la", 2, "Latin"},
    {"lb", 2, "Luxembourgish"},
    {"ln", 2, "Lingala"},
    {"lo", 2, "Lao"},
    {"lt", 3, "Lithuanian"},
    {"lv", 3, "Latvian"},
    {"mg", 2, "Malagasy"},
    {"mi", 3, "Maori"},
    {"mk", 3, "Macedonian"},
    {"ml", 2, "Malayalam"},
    {"mn", 2, "Mongolian"},
    {"mr", 2, "Marathi"},
    {"ms", 1, "Malay"},
    {"mt", 4, "Maltese"},
    {"my", 1, "Burmese"},
    {"nb", 2, "Norwegian Bokmal"},
    {"ne", 2, "Nepali"},
    {"nl", 2, "Dutch"},
    {"nn", 2, "Norwegian Nynorsk"},
    {"nso", 2, "Northern Sotho"},
    {"oc", 2, "Occitan"},
    {"om", 1, "Oromo"},
    {"or", 2, "Odia"},
    {"pa", 2, "Punjabi"},
    {"pl", 3, "Polish"},
    {"ps", 2, "Pashto"},
    {"pt", 2, "Portuguese"},
    {"qu", 2, "Quechua"},
    {"rm", 2, "Romansh"},
    {"rn", 2, "Rundi"},
    {"ro", 3, "Romanian"},
    {"ru", 3, "Russian"},
    {"rw", 2, "Kinyarwanda"},
    {"sa", 3, "Sanskrit"},
    {"sd", 2, "Sindhi"},
    {"se", 3, "Northern Sami"},
    {"si", 2, "Sinhala"},
    {"sk", 3, "Slovak"},
    {"sl", 4, "Slovenian"},
    {"sn", 2, "Shona"},
    {"so", 2, "Somali"},
    {"sq", 2, "Albanian"},
    {"sr", 3, "Serbian"},
    {"ss", 2, "Swati"},
    {"st", 2, "Southern Sotho"},
    {"su", 1, "Sudanese"},
    {"sv", 2, "Swedish"},
    {"sw", 2, "Swahili"},
    {"ta", 2, "Tamil"},
    {"te", 2, "Telugu"},
    {"tg", 2, "Tajik"},
    {"th", 1, "Thai"},
    {"ti", 2, "Tigrinya"},
    {"tk", 2, "Turkmen"},
    {"tn", 2, "Tswana"},
    {"to", 2, "Tongan"},
    {"tr", 1, "Turkish"},
    {"ts", 2, "Tsonga"},
    {"tt", 1, "Tatar"},
    {"ug", 2, "Uyghur"},
    {"uk", 3, "Ukrainian"},
    {"ur", 2, "Urdu"},
    {"uz", 2, "Uzbek"},
    {"vi", 1, "Vietnamese"},
    {"vo", 2, "Volapuk"},
    {"wa", 2, "Walloon"},
    {"wo", 2, "Wolof"},
    {"xh", 2, "Xhosa"},
    {"yi", 2, "Yiddish"},
    {"yo", 1, "Yoruba"},
    {"zh", 1, "Chinese"},
    {"zu", 2, "Zulu"}
};

#endif // LANGUAGES_H
